name: Deploy to prod
env:
  AZURE_WEBAPP_NAME: ttawebpage    # set this to the name of your Azure Web App
  WEB_APP_CSPROJ: './src/TTASLN/TTA.Web/TTA.Web.csproj'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build-deploy-to-azure:
   runs-on: ubuntu-latest
   steps:         
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{env.DOTNET_VERSION}}
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}          
      - name: Build with dotnet on ${{env.WEB_APP_CSPROJ}}
        run: dotnet build --configuration Release ${{env.WEB_APP_CSPROJ}}    
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/webapp ${{env.WEB_APP_CSPROJ}}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}  
         slot-name: 'production'
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         package:  ${{env.DOTNET_ROOT}}/webapp
