name: "Pass parameters to Bicep"
on:  
  workflow_dispatch:
env:
  WORKDIR: "scripts/IaC/Modernization"
  DEFAULT_LOCATION: "westeurope"
  CUSTOMER_NAME: "ama-cust-containers-01"
  REGISTRYNAME: "amaacrregistry"
jobs:
  pass-variables:
    name: 'Login and get variables passed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Login to Azure"
        uses: Azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'     
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
      - name: "Set connection string OUTPUT"
        id: connStringStep
        shell: pwsh
        run: |
          $sqlConnection = az sql db show-connection-string --client ado.net --server sql-${{ env.CUSTOMER_NAME }}
          $sqlConnection = $sqlConnection.replace('<username>', "ttasql")
          $sqlConnection = $sqlConnection.replace('<password>', "Sql@news0l1!")
          $sqlConnection = $sqlConnection.replace('<databasename>', "TTADB")          
          Write-Host $sqlConnection 
          echo "sqlConn=$sqlConnection" >> $Env:GITHUB_OUTPUT     
      - name: "Set connection string ENV"
        id: connStringStepENV
        shell: pwsh
        run: |
          $sqlConnection = az sql db show-connection-string --client ado.net --server sql-${{ env.CUSTOMER_NAME }}
          $sqlConnection = $sqlConnection.replace('<username>', "ttasql")
          $sqlConnection = $sqlConnection.replace('<password>', "Sql@news0l1!")
          $sqlConnection = $sqlConnection.replace('<databasename>', "TTADB")                    
          echo "sqlConn=$sqlConnection" >> $Env:GITHUB_ENV      
      - name: "ConnString test"
        run: |
          echo "${{ steps.connStringStep.outputs.sqlConn }}" 
      - name: "Github ENV test"
        run: |
          echo "${{ env.sqlConn }}"  
      
          
