name: "Deploy containers for a customer"
on:
  push:
    branches:
      - main
    paths:
      - "scripts/IaC/Modernization/**"
  workflow_dispatch:
env:
  WORKDIR: "scripts/IaC/Modernization"
  DEFAULT_LOCATION: "westeurope"
  CUSTOMER_NAME: "ama-cust-containers-01"
  REGISTRYNAME: "amaacrregistry"
jobs:
    container-deployment:
      name: 'Create containers for one customer'
      runs-on: ubuntu-latest      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: "Login to Azure to be able to create container app environment"
          uses: Azure/login@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
        - name: 'Create resource group rg-${{ env.CUSTOMER_NAME }}'
          uses: Azure/cli@v1
          with:
            inlineScript: |
              az deployment sub create \
               --name "${{ env.CUSTOMER_NAME }}-${{ github.run_id }}" \
               --template-file  "${{ env.WORKDIR }}/rg.bicep" \
               --location "${{ env.DEFAULT_LOCATION }}" \
               --parameters resourceGroupName="rg-${{ env.CUSTOMER_NAME }}"    
        - name: 'Create registry in Resource Group rg-${{ env.CUSTOMER_NAME }}'
          uses: Azure/cli@v1
          with:
            inlineScript: |
              az deployment group create \
               --name "reg-${{ env.CUSTOMER_NAME }}-${{ github.run_id }}" \
               --template-file  "${{ env.WORKDIR }}/registry.bicep" \
               --resource-group "rg-${{ env.CUSTOMER_NAME }}" \
               --parameters acrName="${{ env.REGISTRYNAME }}"               
        - name: 'Prepare containers in registry ${{ env.REGISTRYNAME }}'
          uses: Azure/cli@v1
          with:
            inlineScript: |
                az acr build --registry "${{ env.REGISTRYNAME }}" \
                    --image "tta/web:${{ github.run_id }}" \
                    --file "containers/TTA.Web.dockerfile" "src"
                az acr build --registry "${{ env.REGISTRYNAME }}" \
                    --image "tta/webclient:${{ github.run_id }}" \
                    --file "containers/TTA.Web.ClientApi.dockerfile" "src"                          
        - name: 'Create SQL in Resource Group rg-${{ env.CUSTOMER_NAME }}'
          uses: Azure/cli@v1
          with:
            inlineScript: |
              az deployment group create \
               --name "sql-${{ env.CUSTOMER_NAME }}-${{ github.run_id }}" \
               --template-file  "${{ env.WORKDIR }}/sql.bicep" \
               --resource-group "rg-${{ env.CUSTOMER_NAME }}" \
               --parameters administratorLogin="ttasql" administratorLoginPassword="Sql@news0l1!" serverName="sql-${{ env.CUSTOMER_NAME }}" sqlDBName="TTADB"
        - name: 'Add FW rule to SQL in Resource Group rg-${{ env.CUSTOMER_NAME }}'
          uses: Azure/cli@v1
          with:
            inlineScript: |
              az sql server firewall-rule create --resource-group rg-${{ env.CUSTOMER_NAME }} --server sql-${{ env.CUSTOMER_NAME }} --name AllowAzureServices --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0        
        - name: 'Create container app environment in resource Group rg-${{ env.CUSTOMER_NAME }}'
          shell: pwsh
          run: |
              $sqlConnection = az sql db show-connection-string --client ado.net --server sql-${{ env.CUSTOMER_NAME }}
              $sqlConnection = $sqlConnection.replace('<username>', "ttasql")
              $sqlConnection = $sqlConnection.replace('<password>', "Sql@news0l1!")
              $sqlConnection = $sqlConnection.replace('<databasename>', "TTADB")
              $rgPassword = az acr credential show -n "${{ env.REGISTRYNAME }}" --query passwords[0].value
              az deployment group create --name "ce-${{ env.CUSTOMER_NAME }}-${{ github.run_id }}" --template-file  "${{ env.WORKDIR }}/containerapp.bicep" --resource-group "rg-${{ env.CUSTOMER_NAME }}" --parameters location="${{ env.DEFAULT_LOCATION }}" frontendContainerImage="${{ env.REGISTRYNAME }}.azurecr.io/tta/web:${{ github.run_id }}" backendContainerImage="${{ env.REGISTRYNAME }}.azurecr.io/tta/webclient:${{ github.run_id }}" sqlConn="$sqlConnection" registry="${{ env.REGISTRYNAME }}.azurecr.io" registryUsername="${{ env.REGISTRYNAME }}" registryPassword="$rgPassword"       
            
  
          