name: "Deploy Bicep for one customer"
on:
  push:
    branches:
      - main
    paths:
      - "iac/VM/**"
  workflow_dispatch:
env:
  WORKDIR: "iac/VM" 
defaults:
  run:
    working-directory: "iac/VM"
jobs:
  preview:
    name: "Preview Changes"
    runs-on: ubuntu-latest
    outputs:
      RESOURCES_PREFIX: ${{ steps.resources_prefix.outputs.result }}
    steps:      
      - name: Checkout
        uses: actions/checkout@v2      
      - name: Get repo name
        uses: actions/github-script@v5
        id: resources_prefix
        with:
          result-encoding: string
          script: return context.repo.repo.toLowerCase()

      # Login to Azure with Service Principal
      - name: "Login to Azure"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Preview changes
      - name: "What-If"
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az deployment sub what-if \
              --name ${{ github.run_id }} \
              --template-file ${{ env.WORKDIR }}/main.bicep \
              --location "${{ secrets.LOCATION }}" \
              --parameters resourcesPrefix=${{ steps.resources_prefix.outputs.result }}
  deploy:
    name: "Deploy"
    needs: preview
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Login to Azure with Service Principal
      - name: "Azure Login"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Deploy
      - name: "Deployment"
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az deployment sub create \
              --name ${{ github.run_id }} \
              --template-file ${{ env.WORKDIR }}/main.bicep \
              --location "${{ secrets.LOCATION }}" \
              --parameters resourcesPrefix=${{ needs.preview.outputs.RESOURCES_PREFIX }}
