name: "Deploy native resources for one customer"
on:
  push:
    branches:
      - main
    paths:
      - "scripts/IaC/Modernization/**"
  workflow_dispatch:
env:
  WORKDIR: "scripts/IaC/Modernization"
  DEFAULT_LOCATION: "westeurope"
  CUSTOMER_NAME: "ama-cust-containers-01"
defaults:
  run:
    working-directory: "scripts/IaC/Modernization"
jobs:
    vm-deployment:
      name: 'Create containers for one customer and publish the results'
      runs-on: ubuntu-latest
      needs: rg-deployment
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: "Login to Azure to be able to create VM"
          uses: Azure/login@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
        - name: 'Run Powershell script to create resources'
          shell: pwsh
          run: |
            .\azure-creation.ps1 -regionToDeploy ${{ env.DEFAULT_LOCATION }} -containerAppName ${{ env.CUSTOMER_NAME }}